version: '3.1'

services:

  php:
    build: .
    working_dir: '/var/www'
    volumes:
      - './:/var/www:cached'
    # env_file:
    #   - ./.env
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vendor/bin
    hostname: joomla.localhost
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`joomla.localhost`)"
      - "traefik.http.services.php.loadbalancer.server.port=80"

  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    volumes:
      - "../:/var/www/html"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    image: mysql:5.7
    ports:
      - 3306
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example